### ISSUE TITLE
I have issue with the Update profile, just show that I 'Unauthorized user' 

### ISSUE THREAD

**Issue by Serhii-Muzychuk** [gigya/drupal8#98]
I have an issue with the Update profile, just show that I 'Unauthorized user'  when trying to update with custom screen set, 
How I can fix that?

**Comment by Ynhockey** [comment]
Hi Serhii,

This normally happens when the Drupal and Gigya sessions are not synchronizes. This could be a result of incorrect configuration, or occasionally an inherent issue with the setup (Drupal does not allow dynamically changing session configuration, so the module works through revocation). If it's some inherent issue, it can probably be fixed through hooking into the session management process, but it might be more complicated.

In any case, please check that your PHP/Drupal session length is identical to the session type and length set in the module (under Gigya module configuration > RaaS).

**Comment by Serhii-Muzychuk** [comment]
Ok, thanks a lot, will try)

**Comment by Serhii-Muzychuk** [comment]
I've found that happens only in incognito mode, is exist any solution to fix that?
